### ISSUE TITLE
protoc-c segfaults on certain .proto files

### ISSUE THREAD

**Issue by hartwork** [protobuf-c/protobuf-c#223]
Hello!

I hope I'm at the right place to report. To reproduce, please run:
```
# git clone -o github-readonly https://github.com/xemul/criu.git criu-GIT

# cd criu-GIT/

# git checkout -b on-the-same-page 594fb527533f2377e0f98f7d46c00a0ef0219e9c

# protoc-c --version
protobuf-c 1.2.1                                                                                                                                                                             
libprotoc 3.0.0

# protoc-c --proto_path=images/ --c_out=images/ images/stats.proto 2>/dev/null                                                                                                               
Segmentation fault
```
or [download `stats.proto`](https://raw.githubusercontent.com/xemul/criu/master/images/stats.proto), directly.

Best, Sebastian

**Comment by edmonds** [comment]
Hi, Sebastian:

Thanks for the report. It looks like it might be related somehow to protobuf 3, since I can't replicate this on:

```
$ protoc-c --version
protobuf-c 1.2.1
libprotoc 2.6.1
```

I'll try again soon with a protobuf-c built against protobuf 3.

In the mean time, any chance you could run `protoc-c` under gdb and get a backtrace? Something like:

```
gdb --args protoc-c --proto_path=images/ --c_out=images/ images/stats.proto
run
bt full
```

**Comment by hartwork** [comment]
Sure.
```
# gdb -batch -ex run -ex 'bt full' --args protoc-c --proto_path=images/ --c_out=images/ images/stats.proto 2>/dev/null 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000000000041808b in google::protobuf::compiler::c::FilenameIdentifier(std::string const&) ()
#0  0x000000000041808b in google::protobuf::compiler::c::FilenameIdentifier(std::string const&) ()
No symbol table info available.
#1  0x00000000004155e4 in google::protobuf::compiler::c::FileGenerator::GenerateHeader(google::protobuf::io::Printer*) ()
No symbol table info available.
#2  0x00000000004167b9 in google::protobuf::compiler::c::CGenerator::Generate(google::protobuf::FileDescriptor const*, std::string const&, google::protobuf::compiler::GeneratorContext*, std::string*) const ()
No symbol table info available.
#3  0x00007ffff79ee07d in google::protobuf::compiler::CommandLineInterface::GenerateOutput(std::vector<google::protobuf::FileDescriptor const*, std::allocator<google::protobuf::FileDescriptor const*> > const&, google::protobuf::compiler::CommandLineInterface::OutputDirective const&, google::protobuf::compiler::GeneratorContext*) () from /usr/lib64/libprotoc.so.10
No symbol table info available.
#4  0x00007ffff79ef0b2 in google::protobuf::compiler::CommandLineInterface::Run(int, char const* const*) () from /usr/lib64/libprotoc.so.10
No symbol table info available.
#5  0x00000000004038da in main ()
No symbol table info available.
```
Let me know if you need anything more.

**Comment by hartwork** [comment]
After re-compiling protobuf-c the segfaults went away with me. I guess it's not a bug but ABI-incompatibility of 2.6.1 to 3.0.0?

**Comment by edmonds** [comment]
That's really weird. Isn't protobuf 3.0.0 using different SONAMEs from protobuf 2.6.1?

**Comment by hartwork** [comment]
Good point, I confirm different sonames (.so.9 versus .so.10).
My new guess was that I still had the old 2.6.1 .so.9 files around but they were used with 3.0.0 data files and that they don't mix well. While I am sure now that combination was the case when the segfaults showed to me, I can no longer reproduce the segfaults by forcing that very condition.

By now I feel like I'm wasting your time with something that is not actually a bug. As far as I am concerned, I am all good if you close the bug.

Best, Sebastian

**Comment by edmonds** [comment]
OK, glad it worked out for you.
