### ISSUE TITLE
String fields are not validated for UTF-8 correctness

### ISSUE THREAD

**Issue by TimWolla** [protobuf-c/protobuf-c#726]
Consider the follow Proto file:

```protobuf
syntax="proto3";

message MyMessage {
	string my_string = 1;
}
```

And the following Payload:

base64: `CgLwgA==`
bytes: `0x0a, 0x02, 0xf0, 0x80`
escape: `"\x0a\x02\xf0\x80"`

The contained string sequence is `\xf0\x80`, which is not valid UTF-8.

Attempting to decode it with protobuf-c using the follow example:

```c
#include "./bug.pb-c.h"
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>

void *my_malloc(void *unused, size_t len)
{
	return malloc(len);
}

void my_free(void *unused, void *ptr)
{
	free(ptr);
}

int
main(void) {
	ProtobufCAllocator alloc = {
		.alloc = my_malloc,
		.free = my_free,
		.allocator_data = NULL,
	};

	MyMessage *r;
	r = my_message__unpack(&alloc, 4, "\x0a\x02\xf0\x80");
	printf("%s", r->my_string);

	return 0;
}
```

will successfully decode the payload and print `\xf0\x80`.

Attempting to decode it with the C++ implementation using:

```cpp
#include <iostream>
#include <fstream>
#include "./bug.pb.h"

unsigned char invalid_utf8[] = {
  0x0a, 0x02, 0xf0, 0x80
};
unsigned int invalid_utf8_len = 4;

int
main(void) {
	std::fstream input("../c/out", std::ios::in | std::ios::binary);

	MyMessage r;
	r.ParseFromArray(invalid_utf8, invalid_utf8_len);
}
```

outputs:

```
[libprotobuf ERROR google/protobuf/wire_format_lite.cc:618] String field 'MyMessage.my_string' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
```

Likewise the PHP implementation using:

```php
<?php

require('vendor/autoload.php');

spl_autoload_register(function ($class) {
	$filename = __DIR__ . "/php/" . str_replace('\\', '/', $class) . '.php';
	if (file_exists($filename)) {
		require_once($filename);
	}
});

$loaded = new MyMessage();
$loaded->mergeFromString("\x0a\x02\xf0\x80");
var_dump($loaded);
```

outputs:

```
PHP Fatal error:  Uncaught Exception: Expect utf-8 encoding. in vendor/google/protobuf/src/Google/Protobuf/Internal/GPBUtil.php:80
Stack trace:
#0 php/MyMessage.php(49): Google\Protobuf\Internal\GPBUtil::checkString()
#1 vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(518): MyMessage->setMyString()
#2 vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(790): Google\Protobuf\Internal\Message->parseFieldFromStream()
#3 vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(753): Google\Protobuf\Internal\Message->parseFromStream()
#4 bug.php(13): Google\Protobuf\Internal\Message->mergeFromString()
#5 {main}
  thrown in vendor/google/protobuf/src/Google/Protobuf/Internal/GPBUtil.php on line 80
```

-----------------------

`string` fields are defined to be valid UTF-8 and this is validated for both C++ and PHP. Validation should also be added to protobuf-c.

**Comment by edmonds** [comment]
I agree that the protobuf `string` type is defined as only containing UTF-8 encoded strings, however the protobuf-c implementation has historically not validated this for the caller. If the caller requires that a string only contain UTF-8 data then the caller needs to perform that validation on the returned data. We also cannot represent strings with embedded NULs which I believe is allowed by the protobuf `string` type.

**Comment by TimWolla** [comment]
> If the caller requires that a string only contain UTF-8 data then the caller needs to perform that validation on the returned data.

This is not just an issue for receiving and parsing a protobuf message, but also for encoding and sending one. It is easy to accidentally include non-UTF-8 data in a string field, leading to the recipient rejecting the protobuf message as malformed, which is not something expected by the user when using a schema-based encoding format.

> We also cannot represent strings with embedded NULs which I believe is allowed by the protobuf `string` type.

Yes, a NUL may appear in a protobuf string (the C++ implementation accepts them). Handling these in protobuf-c is already possible using the `string_as_bytes` field option.
